server {
    listen 80;
    server_name lucidiusss.ru;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }

    location /_next/static {
        alias /usr/share/nginx/html/_next/static;
        expires 365d;
        access_log off;
    }

    location /static {
        alias /usr/share/nginx/html/static;
        expires 365d;
        access_log off;
    }
}
